### ISSUE TITLE
Training division by 0 error

### ISSUE THREAD

**Issue by HRezaeiM** [ProsusAI/finBERT#12]
Thanks for sharing your code on this matter. I have used your trained model. however, I want to try and train the model on my own with the help of the datasets which you have mentioned. 
But with running the `finbert_training.ipynb` I hit to an error on `trained_model = finbert.train(train_examples = train_data, model = model)` 
![Screenshot from 2020-02-13 12-38-50](https://user-images.githubusercontent.com/25917418/74466936-d3c43e00-4e5d-11ea-8a86-92bfc4141856.png)

I have tried to debug the code, for some reasons step is always 0. I was wondering if you can give me some hints on the hint on how to fix this issue :)

**Comment by doguaraci** [comment]
Hi! I see from the screenshot you shared that `num_examples` is 1. That means there is only one example in the training data set. Could you check if you're loading the training data correctly?

**Comment by MonicaFurdui** [comment]
I am having the same error now as the user above and my Num examples =7 (for testing) . Batch size=32 and Num steps=0
Can you please help out? thanks !
