### ISSUE TITLE
Vocabulary 

### ISSUE THREAD

**Issue by avramandrei** [ProsusAI/finBERT#13]
Hello,

Could you include the `vocab.txt` for finBERT? I don't see it in the model's directory and it seems like you are using `bert-base-uncased` vocabulary for constructing the tokenizer ( https://github.com/ProsusAI/finBERT/blob/master/finbert/finbert.py)
```
self.tokenizer = BertTokenizer.from_pretrained("bert-base-uncased", do_lower_case=self.config.do_lower_case)
```

Thank you,
Andrei

**Comment by bernardmizzi** [comment]
Dear Andrei, did you manage to run cell 'Configuring training parameters' in the note book finbert_training.ipynb?

**Comment by avramandrei** [comment]
I have seen your issue with the configuration parameters. Unfortunately, I did not run the notebook. I only wanted to load finBERT in my program. 

> Dear Andrei, did you manage to run cell 'Configuring training parameters' in the note book finbert_training.ipynb?

**Comment by bernardmizzi** [comment]
> I have seen your issue with the configuration parameters. Unfortunately, I did not run the notebook. I only wanted to load finBERT in my program.
> 
> > Dear Andrei, did you manage to run cell 'Configuring training parameters' in the note book finbert_training.ipynb?

I fixed the issue, thanks anyways :)
