### ISSUE TITLE
Unable to download models 

### ISSUE THREAD

**Issue by nazihkalo-uchicago** [ProsusAI/finBERT#15]
I am unable to download files through git-lfs because 
"" This repository is over its data quota. Account responsible for LFS bandwidth should purchase 
more data packs to restore access. ""

Could you please provide the models through an alternate resource or upgrade the LFS data packs? If that is not possible could you provide the train/test/validation sets used to train the classifier? Thank you!
<img width="1028" alt="image" src="https://user-images.githubusercontent.com/59754580/77934542-d8aa4900-7275-11ea-97f0-701a47912e87.png">

**Comment by l0rem1psum** [comment]
I believe you can a copy of the model file in this issue: #14.

**Comment by doguaraci** [comment]
You can download it directly from GitHub.

**Comment by metodj** [comment]
I just got the same error after using git-lfs to clone the repo. When downloading directly from git (i.e. clicking raw, then right click and save as) I only get the 3 lines text file instead of 400MB model file. Could you perhaps upload the model to some other place from where we could download it? thanks!

**Comment by Gashbell** [comment]
I also have the same problem of not being able to download the full model files. States the repo is over its data quote.

**Comment by jarasny** [comment]
Same error here. Not able to download it by git-lfs or directly from GitHub. In other issue someone uploaded it to google drive but the link expired.

**Comment by doguaraci** [comment]
Please check the updated README. We don't use git-lfs anymore.
