### ISSUE TITLE
pytorch_model.bin file

### ISSUE THREAD

**Issue by zoey-lyu** [ProsusAI/finBERT#18]
Hi! 

I just downloaded this .bin file and was wondering how to get the following two files(Language model trained on TRC2
 & Sentiment analysis model trained on Financial PhraseBank) from it?

Thanks!!

**Comment by sharon-gao** [comment]
I have the same question.
Some one mentioned in [https://github.com/ProsusAI/finBERT/issues/8#issuecomment-568299104](url) that the model pertained on TRC2 should be placed in the directory `models/language_model/finbertTRC2/pytorch_model.bin`, but when I followed this it failed. The error is 
`FileNotFoundError: [Errno 2] No such file or directory: '/Users/gaoshuang/Desktop/finBERT/models/language_model/finbertTRC2/bert_config.json'`

**Comment by sharon-gao** [comment]
I solved this problem by placing the models in the directory mentioned above and adding the config.json to the same directory. Actually the author has written the steps in `README` **Models**.

**Comment by akmalsabri** [comment]
but where to find the bert_config.json file ?
