### ISSUE TITLE
how to create train.csv, validation.csv, test.csv

### ISSUE THREAD

**Issue by akmalsabri** [ProsusAI/finBERT#19]
Hi, how to setup and create train.csv, validation.csv, test.csv from Financial Pharase Bank data?

**Comment by emes83** [comment]
> Hi, how to setup and create train.csv, validation.csv, test.csv from Financial Pharase Bank data?

The same here.

**Comment by akmalsabri** [comment]
@emes83 or maybe  we need to create them on our own from the link https://www.researchgate.net/publication/251231364_FinancialPhraseBank-v10

**Comment by emes83** [comment]
> @emes83 or maybe we need to create them on our own from the link https://www.researchgate.net/publication/251231364_FinancialPhraseBank-v10

Maybe, I believe that, yes, but how?.  I'm wondering how to do this to adapt the solution to another language in the future.

**Comment by akmalsabri** [comment]
@emes83 i try this data . https://github.com/ProsusAI/finBERT/issues/5#issuecomment-647893530 .maybe you should try.
 But still ,I get error `IndexError: list index out of range
` when running `train_data = finbert.get_data('train')`

**Comment by emes83** [comment]
> @emes83 i try this data . [#5 (comment)](https://github.com/ProsusAI/finBERT/issues/5#issuecomment-647893530) .maybe you should try.
> But still ,I get error `IndexError: list index out of range ` when running `train_data = finbert.get_data('train')`

The same here.

**Comment by MonicaFurdui** [comment]
I am getting the same error IndexError: list index out of range and the dataset in the link has invalid characters as well. Anyone could fix the issue?

**Comment by emes83** [comment]
Can somebody please share train/validation/test files? In proper/working format?

**Comment by valentintsl** [comment]
Hello mates !
After doing a thorough search of the program, I found the architecture of the train, test, validation inputs.
The csv files need to have the following column names [text, label] WITH THE INDEX.
The data needs to be separated by tab '\t'.

I attach the csv files for the Financial Phrase Bank dataset that I made.

[FinancialPhraseBankforFinBERT.zip](https://github.com/ProsusAI/finBERT/files/5079542/FinancialPhraseBankforFinBERT.zip)

Valentin TASSEL

**Comment by evanzd** [comment]
The labels provided by @valentintsl are not balanced. I'm using the script below to create these datasets:
```python
import pandas as pd

with open('Sentences_50Agree.txt', 'rb') as f:
    data = f.read().decode(errors='ignore')

df = pd.DataFrame([x.split('@') for x in data.strip().split('\r\n')], columns=['text', 'label'])

pos = df.query('label=="positive"')
pos = pos.sample(len(pos), random_state=0) # shuffle samples

neg = df.query('label=="negative"')
neg = neg.sample(len(neg), random_state=0)

neu = df.query('label=="neutral"')
neu = neu.sample(len(neu), random_state=0)

n_pos = int(len(pos)*0.2)
n_neg = int(len(neg)*0.2)
n_neu = int(len(neu)*0.2)

pd.concat([pos[:-n_pos*2], neg[:-n_neg*2], neu[:-n_neu*2]], axis=0).to_csv('train.csv', sep='\t')
pd.concat([pos[-n_pos*2:-n_pos], neg[-n_neg*2:-n_neg], neu[-n_neu*2:-n_neu]], axis=0).to_csv('validation.csv', sep='\t')
pd.concat([pos[-n_pos:], neg[-n_neg:], neu[-n_neu:]], axis=0).to_csv('test.csv', sep='\t')
```

**Comment by nithinreddyy** [comment]
`trained_model = finbert.train(train_examples = train_data, model = model)`

Error is

```
TypeError                                 Traceback (most recent call last)
<ipython-input-11-2ebf0cb3d4e8> in <module>
----> 1 trained_model = finbert.train(train_examples = train_data, model = model)

~\finBERT-master\finbert\finbert.py in train(self, train_examples, model)
    482                     print('No best model found')
    483                 torch.save({'epoch': str(i), 'state_dict': model.state_dict()},
--> 484                            self.config.model_dir / ('temporary' + str(i)))
    485                 best_model = i
    486 

TypeError: unsupported operand type(s) for /: 'str' and 'str'
```

**Can anyone check this and help me, please?**

**Comment by doguaraci** [comment]
You can find the instructions to create these files on the updated README.
