### ISSUE TITLE
sample set of TRC2

### ISSUE THREAD

**Issue by vr25** [ProsusAI/finBERT#2]
Hi,

Since the TRC2 dataset cannot be publicly made available, I was wondering if some similar format sample training dataset can be provided. 

Thanks!

**Comment by doguaraci** [comment]
Hi,

There is a much smaller and older (but public) dataset called Reuters-21578 (https://archive.ics.uci.edu/ml/machine-learning-databases/reuters21578-mld/). The only format requirement for language model training is that sentences should be separated by one new line and documents with two new lines. This can of course be changed in the language model pre-training script. 

Hope this helps.

**Comment by vr25** [comment]
Thank you so much for your reply and for sharing the link.
