### ISSUE TITLE
Update the environment file

### ISSUE THREAD

**Issue by abhishekpalit09** [ProsusAI/finBERT#21]
Hi,

I am trying to setup the environment. It always pops up with pip & torch version error. Can you please update the yml for me?
Wanted to check your solution.

**Comment by doguaraci** [comment]
Hello, I can try to help if you could share the actual error. 

Are you using Windows?

**Comment by abhishekpalit09** [comment]
Hi,

I have upgraded the python version and it worked for me. Thanks
