### ISSUE TITLE
loading pytorch_model.bin

### ISSUE THREAD

**Issue by sanjayb678** [ProsusAI/finBERT#22]
I downloaded and placed the language model (pytorch_model.bin) and config.json in the same directory and when i run the piece of code: configuring training parameters, get below error:

INFO - pytorch_pretrained_bert.modeling - loading archive file /directory/pytorch_model.bin
INFO - pytorch_pretrained_bert.modeling - extracting archive file /directory/pytorch_model.bin to temp dir /tmp/tmppjpupb
Readerror: not a gzip file

Looking more granular:
/usr/lib/python3.6/tarfile.py in gzopen(cls, name, mode, fileobj, compresslevel, **kwargs)
1645 fileobj.close()
1646 if mode == 'r':
-> 1647 raise ReadError("not a gzip file")
1648 raise
1649 except:

**Comment by drk3931** [comment]
zip the bin file and config.json into a .tar.gz file 
or alternatively you can put them into a directory and turn cache_dir on
model = BertForSequenceClassification.from_pretrained('./location_of_bin/',num_labels=3,cache_dir=True)

**Comment by hartblanc** [comment]
It could be useful to include this in README.md under ##models
