### ISSUE TITLE
torch error / environment file on windows

### ISSUE THREAD

**Issue by MatthAp** [ProsusAI/finBERT#24]
Hi,

When installing the environment file the following error occurs: 

```
Pip subprocess output:
Collecting joblib==0.13.2
  Using cached joblib-0.13.2-py2.py3-none-any.whl (278 kB)
Collecting pytorch-pretrained-bert==0.6.2
  Using cached pytorch_pretrained_bert-0.6.2-py3-none-any.whl (123 kB)
Collecting scikit-learn==0.21.2
  Using cached scikit_learn-0.21.2-cp37-cp37m-win_amd64.whl (5.9 MB)
Collecting spacy==2.1.4
  Using cached spacy-2.1.4-cp37-cp37m-win_amd64.whl (29.0 MB)

Pip subprocess error:
ERROR: Could not find a version that satisfies the requirement torch==1.1.0 (from -r C:\Users\Matth\condaenv.xiuu97lv.requirements.txt (line 5)) (from versions: 0.1.2, 0.1.2.post1, 0.1.2.post2)
ERROR: No matching distribution found for torch==1.1.0 (from -r C:\Users\Matth\condaenv.xiuu97lv.requirements.txt (line 5))


CondaEnvException: Pip failed
```

As a consequence packages can not be loaded successfully in the created environment.

The error seems common for windows users ( #21 ). However, updating python did not do the trick for me here.

I use Win 10, python version(3.7.7), torch version (1.5.1) and conda version (4.8.3).

Hopefully you can provide me with some assistance to get FinBert up and running on windows.

**Comment by drk3931** [comment]
try conda install pytorch==1.1.0 torchvision==0.3.0 cudatoolkit=10.0 -c pytorch.
The windows subystem for linux also works.

**Comment by MatthAp** [comment]
Thanks, solved by doing the following:

1) conda create --name finbert pytorch==1.1.0 torchvision==0.3.0 cudatoolkit=10.0 -c pytorch

2) conda env update --name finbert --file environment.yml
