### ISSUE TITLE
What is the news_id?

### ISSUE THREAD

**Issue by RawCheer** [ProsusAI/finBERT#25]
Could anyone explain what is the news_id in predict()?
<img width="727" alt="Screen Shot 2020-07-28 at 9 35 17 PM" src="https://user-images.githubusercontent.com/47097945/88746440-62bdcd80-d101-11ea-848e-f57c8904010b.png">
<img width="968" alt="Screen Shot 2020-07-28 at 9 35 33 PM" src="https://user-images.githubusercontent.com/47097945/88746444-66e9eb00-d101-11ea-86f6-8471d75c980d.png">

**Comment by gench** [comment]
It must be your own addition, predict function in FinBERT doesnt have such a parameter.
```
def predict(text, model, write_to_csv=False, path=None):
    """
    Predict sentiments of sentences in a given text. The function first tokenizes sentences, make predictions and write
    results.
    Parameters
    ----------
    text: string
        text to be analyzed
    model: BertForSequenceClassification
        path to the classifier model
    write_to_csv (optional): bool
    path (optional): string
        path to write the string
    """
```
