### ISSUE TITLE
Does it support paragraph prediction?

### ISSUE THREAD

**Issue by LucasAndLevinAndJadon** [ProsusAI/finBERT#26]
I am predicting paragraph based on this model.
The output separates sentences randomly.
Certainly it has something to do with the fast the my data text is not clean. 
I wonder whether this is a need for some others too. 
Thank you.

**Comment by gench** [comment]
BERT has a max length limit of 512 tokens. It does not do any sentence-segmentation but treat the given input text as it is. You can segment your paragraph into sentences and calculate the sentence-based sentiment. Then, calculate paragraph-level sentiment over those.
