### ISSUE TITLE
How much improvement do you see with "discriminative fine-tuning" and "Gradual Unfreezing"?

### ISSUE THREAD

**Issue by vgoklani** [ProsusAI/finBERT#36]
Hey there,

How much improvement do you see with "discriminative fine-tuning" and "Gradual Unfreezing"?

Could you quantify the improvement?

i.e.:

> 1%
> 5%

thanks!

**Comment by doguaraci** [comment]
Hi you can check the results on the [paper](https://arxiv.org/abs/1908.10063). Table 5 has the relevant information.
