### ISSUE TITLE
How can we launch the finebert_training on multiple servers

### ISSUE THREAD

**Issue by ngobibibnbe** [ProsusAI/finBERT#37]
I have seen that your training implementation of FinBERT supports distributed training. But how can we launch it on multiple servers ?

**Comment by doguaraci** [comment]
Hi, we haven't tried training on multiple servers. 🤗 Transformers have [resources](https://huggingface.co/transformers/v1.2.0/examples.html#introduction) about this. I'd suggest checking them.

**Comment by ngobibibnbe** [comment]
Finally, i trained it on multiple machines within an Hadoop cluster using Horovod to distribute the training process with the allreduce strategy and store the dataset on HDFS. Thank you for your answer.
