### ISSUE TITLE
Could finBERT only give one result (logit / prediction / sentiment_score) for entire article ?

### ISSUE THREAD

**Issue by rockallorange** [ProsusAI/finBERT#39]
Hi, I'm trying to use predict.py, colud it possible to predict entire artile (maybe 17 lines) to one final result? but not 17 result for every sentence ?

The images show 17 lines in green background, each line get a result, could it just predict the entire article(yellow background) ?

Thanks for your help.

![image](https://user-images.githubusercontent.com/38206059/107112168-76a47200-6890-11eb-8cf5-fd94533a6d19.png)

**Comment by doguaraci** [comment]
I'm afraid not. Sentences should have a token length of maximum 64. (Somewhat more is also fine most of the time, only now that the tokenizer is going to truncate part of the text). Averaging the sentiment scores is probably the only solution.
