### ISSUE TITLE
The vocab.txt for finbertTRC2 model

### ISSUE THREAD

**Issue by Vitvicky** [ProsusAI/finBERT#4]
Hi Sir,
Thank you so much for sharing the code.
I notice that in finbertTRC2 folder, the vocab.txt file is missing, could you tell me where I could find this file?

Thanks!

**Comment by doguaraci** [comment]
Hi, we didn't use any other vocab.txt than the one used in bert-base-uncased. You can use that tokenizer.

**Comment by Vitvicky** [comment]
@doguaraci Hi sir, thanks for your response, here I mean that after fine-tuning operation on our own corpus, the original vocab.txt should be changed, is your vocab.txt file also changed during the TRC2 dataset fine-tuning operation? Thanks

**Comment by doguaraci** [comment]
Hi again. I don't think it did. We used an older version of the fine tuning script, which doesn't modify the vocab.txt as far as I now.
