### ISSUE TITLE
How to install and get the financial tweet sentiment score using finbert

### ISSUE THREAD

**Issue by tahapandoratech** [ProsusAI/finBERT#41]
Dear Sir,
I hope this email finds you well.I am new to data science and for my course project I need to use finbert for get the tweet sentiment score and I am unable to install the finbert on pycharm kindly help me on this Thank you

Best Regards
Taha Ahmad

**Comment by doguaraci** [comment]
Hi Taha, could you please be more specific? What do you mean by "installing on pycharm"? Did you try running the steps on the readme?

**Comment by Vishal-Mendekar** [comment]
Hi I have the below version installed in my system
Python 3.6.0
Anaconda 4.9.2
torch 1.8.0

I have cloned finBERT in my Drive. But when I am running this command on the conda prompt "conda env create -f environment.yml" I am getting this error message.

**Pip subprocess error:
ERROR: Could not find a version that satisfies the requirement torch==1.1.0 (from -r C:\Users\Vishal Mendekar\finBERT\condaenv.xiuhwud4.requirements.txt (line 4)) (from versions: 0.1.2, 0.1.2.post1, 0.1.2.post2, 1.7.0, 1.7.1, 1.8.0)
ERROR: No matching distribution found for torch==1.1.0 (from -r C:\Users\Vishal Mendekar\finBERT\condaenv.xiuhwud4.requirements.txt (line 4))
failed
CondaEnvException: Pip failed**

I tried installing torch version 1.1.0 manually but it gives the error **"No such distribution found"**.

How can I get this initial setup thing to work properly in my system?

By default, I had python 3.9.1 in my system but I downgraded it to 3.6.0 thinking maybe it will help. But it didn't.

Also please tell do running finBERT has got anything to do with Python's version.

**Comment by doguaraci** [comment]
We didn't test the code on Windows. I'd suggest to try running it on Linux or MacOS if possible. Or you can use Google colab.

**Comment by Vishal-Mendekar** [comment]
What you mean by running Google colab? Are you trying to say I should train the whole model again or something else. I am a bit confused with your statement.

**Comment by Vishal-Mendekar** [comment]
One more thing to add. In the environemnt.yml file, there are dependencies with their versions mentioned. Like this

   jupyter=1.0.0
   pandas=0.23.4
   python=3.7.3
   numpy==1.16.3
   ipykernel=5.1.3
   transformers=4.1.1
   pip:
   joblib==0.13.2
   scikit-learn==0.21.2
   spacy==2.1.4
   torch==1.1.0

Since all these dependencies have got their upgraded versions. Do we still need to install these specific versions? or it's fine to have the latest one. More specifically can't I use torch 1.8.0
@doguaraci @theofpa @pvdb2178

**Comment by doguaraci** [comment]
> What you mean by running Google colab? Are you trying to say I should train the whole model again or something else. I am a bit confused with your statement.

I suggested this as an alternative to running on Windows. You can run any part of code on Google colab. Unless you are planning to use FinBERT on a production system, Colab is a good option.

**Comment by doguaraci** [comment]
> One more thing to add. In the environemnt.yml file, there are dependencies with their versions mentioned. Like this
> 
> jupyter=1.0.0
> pandas=0.23.4
> python=3.7.3
> numpy==1.16.3
> ipykernel=5.1.3
> transformers=4.1.1
> pip:
> joblib==0.13.2
> scikit-learn==0.21.2
> spacy==2.1.4
> torch==1.1.0
> 
> Since all these dependencies have got their upgraded versions. Do we still need to install these specific versions? or it's fine to have the latest one. More specifically can't I use torch 1.8.0

Those versions are the ones we tested and verified the code for. You can of course try with torch 1.8.0. It'd probably work, but hard to tell without trying.

**Comment by tahapandoratech** [comment]
Can you please send me the steps how to run finbert on google colab.
