### ISSUE TITLE
How to use finBERT using Hugging Face model?

### ISSUE THREAD

**Issue by haylee111** [ProsusAI/finBERT#42]
**I tried this code**
```
from transformers import AutoTokenizer, AutoModelForSequenceClassification
import torch
import numpy as np

tokenizer = AutoTokenizer.from_pretrained("ProsusAI/finbert")
model = AutoModelForSequenceClassification.from_pretrained("ProsusAI/finbert")
```
**but get this error.**

```
OSError: Can't load 'ProsusAI/finbert'. Make sure that:

- 'ProsusAI/finbert' is a correct model identifier listed on 'https://huggingface.co/models'

- or 'ProsusAI/finbert' is the correct path to a directory containing a 'config.json' file

**Comment by doguaraci** [comment]
This is a problem with the transformers library. Please see the discussion [here](https://github.com/huggingface/transformers/issues/353).

**Comment by haylee111** [comment]
Thank you, for the response !

**Comment by miguelperosanz** [comment]
Any update here? I have the same issue, ProsusAI/finbert does not load. I have the feeling the company ProsusAI decided to remove it from the models list?

**Comment by doguaraci** [comment]
Hi the model is there. Like I said, this is an issue not related to us. Please see the discussion [here.](https://github.com/huggingface/transformers/issues/353)
