### ISSUE TITLE
pre-training script on trc2

### ISSUE THREAD

**Issue by novacp** [ProsusAI/finBERT#43]
Hi there, great work and thanks for sharing *star*!

I am currently trying to reproduce pre-training of bert using trc2 corpus for research purposes to which I have access to, so this is not a request for data. Instead, could you please share the pre-processing code you used for pre-training bert to produce finBERT, how you ingested the data into bert pre-training etc.?

Best regards-

**Comment by novacp** [comment]
Duplicate of: https://github.com/ProsusAI/finBERT/issues/1 though I don't know if they could make a working example, I will close this.

**Comment by novacp** [comment]
I had a look at the other threads but I cannot find your pre processing code for trc2 corpus, just pre-training code for bert variants. Could you please share you pre-processing code for trc2? I am wondering if I need another classifier upfront to decide if a document is about finance or not, because trc2 dataset contains a lot of news articles..

**Comment by doguaraci** [comment]
We had a list of 50 finance-related words. And included the document, if the document included any of them. That was the only pre-processing we did.
