### ISSUE TITLE
finBERT pretained model giving issues while calling it

### ISSUE THREAD

**Issue by Vishal-Mendekar** [ProsusAI/finBERT#44]
Hi, I have ubuntu version 16. And I have cloned finBERT in my machine. I have also created a folder and have put the required files from **hugging face** website. Everything was working fine I had got the environment created by running environment.yml file provided in GitHub.

But when I am calling AutoModelForSequenceClassification.from_pretrained(file_path, cache_dir=None, num_labels=3)

**1.** I am getting **Unable to open file (file signature not found)** error.

**2.** Also, when I am checking for version of torch. It's 1.1.0 in my terminal whereas it is 1.6.0 in the jupyter notebook.

All this code is being executed in **Jupyter Notebook**

 

Here is the image of error I am getting
![image](https://user-images.githubusercontent.com/54699229/112293573-4be37100-8cb8-11eb-8a2d-bf630f2f97b1.png)

**Comment by doguaraci** [comment]
Can you share what `file_path` is and the contents of the folder?

You should also make sure you're using the environment you intend to use in Jupyter. You can check that with Kernel menu on the Jupyter notebook.

**Comment by Vishal-Mendekar** [comment]
When I checked in Kernel menu it had only 1 option **Python 3**.
![kernel](https://user-images.githubusercontent.com/54699229/114978711-3cb2a600-9ea7-11eb-8cdb-5bd4bbbd8561.PNG)


I am attaching the snapshot of folder's content and the filepath

**Filepath**
![filepath](https://user-images.githubusercontent.com/54699229/114976952-7c2bc300-9ea4-11eb-84f7-3327cf0e811e.png)

**Folder's Content**

![folder content](https://user-images.githubusercontent.com/54699229/114976976-877eee80-9ea4-11eb-9954-bdc60a243d22.png)

**Comment by sleung852** [comment]
you need to open a terminal and type:
`conda activate finbert`
`conda install -c anaconda ipykernel`
`python -m ipykernel install --user --name=finbert`

now you can go to your notebook and choose the kernel 'finbert'
