### ISSUE TITLE
Dot at the end of short sentences

### ISSUE THREAD

**Issue by metodj** [ProsusAI/finBERT#45]
I was playing around with the finBERT model a bit and I noticed that for short sentences having a period at the end makes a big difference on the model's predictions (see Figures 1-2 below).

Any idea why that is the case? Could it be that the model was fine-tuned on the sentences with a dot at the end and that's why it makes such a difference? Or does it have to do with BERT embeddings, i.e. is there a special embedding for a dot?

#### Figure 1 (short sentence, no period at the end):
![image](https://user-images.githubusercontent.com/20437515/113290689-4c9c8880-92f2-11eb-8b83-a999550db46b.png)

#### Figure 2 (short sentence, a period at the end):
![image](https://user-images.githubusercontent.com/20437515/113290746-5cb46800-92f2-11eb-9a00-6002aa44ab03.png)

**Comment by doguaraci** [comment]
Thanks for raising this, wasn't aware of this behaviour. My guess is that your first potential reason is correct. All the sentences in the data were properly written. Lack of dot might be causing some confusion. Will do more checks.

**Comment by luke4u** [comment]
I can confirm this again, and would be good to have a in-depth review!
