### ISSUE TITLE
Error when calling finbert.train()

### ISSUE THREAD

**Issue by dbejarano31** [ProsusAI/finBERT#46]
I'm trying to run FinBERT for stock market prediction based on SEC filings. I am using the finbert_training notebook as a reference. 

When running:

`trained_model = finbert.train(train_examples = train_data, model = model)` I get the following error:

![Screen Shot 2021-04-12 at 17 23 41](https://user-images.githubusercontent.com/67240653/114419955-2c06e500-9bb4-11eb-92f2-f088fd9c2306.png)

I ran the dataset.py script, and my dataset looks like this: 
![Screen Shot 2021-04-12 at 17 27 09](https://user-images.githubusercontent.com/67240653/114420160-5fe20a80-9bb4-11eb-8932-501e46ac88d5.png)

Could you please guide me as for what I could do? 

Thank you!

**Comment by doguaraci** [comment]
Hi, you should change the `finbert.py` code [here](https://github.com/ProsusAI/finBERT/blob/43f26c88561ff55412ceb86e2993ff92be938928/finbert/finbert.py#L598) with your labels:
