### ISSUE TITLE
Where is the config.json for Sentiment analysis model trained on Financial PhraseBank

### ISSUE THREAD

**Issue by oonisim** [ProsusAI/finBERT#47]
Please provide the information where to download the config.json for ```Sentiment analysis model trained on Financial PhraseBank```

The instruction says to place a copy of ```config.json```. The link to download the ```Sentiment analysis model trained on Financial PhraseBank``` is the bin file only, not include the ```config.json```.

>For both of these model, the workflow should be like this:
>
>Create a directory for the model. For example: models/sentiment/<model directory name>
>Download the model and put it into the directory you just created.
>**Put a copy of config.json in this same directory.**    <------------------------------
>Call the model with .from_pretrained(<model directory name>)

The [config.json in the huggingface](https://huggingface.co/ProsusAI/finbert/blob/main/config.json) looks to be for TRC2.
```
{
  "_name_or_path": "/home/ubuntu/finbert/models/language_model/finbertTRC2",   <-----
  "architectures": [
    "BertForSequenceClassification"
  ],
  "attention_probs_dropout_prob": 0.1,
  "gradient_checkpointing": false,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "id2label": {
    "0": "positive",
    "1": "negative",
    "2": "neutral"
  },
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "label2id": {
    "positive": 0,
    "negative": 1,
    "neutral": 2
  },
  "layer_norm_eps": 1e-12,
  "max_position_embeddings": 512,
  "model_type": "bert",
  "num_attention_heads": 12,
  "num_hidden_layers": 12,
  "pad_token_id": 0,
  "position_embedding_type": "absolute",
  "type_vocab_size": 2,
  "vocab_size": 30522
}
```

**Comment by doguaraci** [comment]
Hi, you can use the same config for FinBERT as well.
