### ISSUE TITLE
Sentiment classifier finetuning Input Format

### ISSUE THREAD

**Issue by abhijeet3922** [ProsusAI/finBERT#5]
Hi,

Thanks for sharing the work.
In order to run notebook "finbert_training.ipynb" for finetuning a sentiment classifier, I could not understand the train.csv (test,validation) format.
Financial Phrase Bank dataset has files where the sentences and labels are separated by @.

Can you tell me the format of these csv files in which it should be prepared ?

I see the following code for reading .csv in utils.py but could not get it.

```@classmethod
    def _read_tsv(cls, input_file):
        """Reads a tab separated value file."""
        with open(input_file, "r") as f:
            reader = csv.reader(f, delimiter="\t")
            lines = []
            for line in reader:
                if sys.version_info[0] == 2:
                    line = list(unicode(cell, 'utf-8') for cell in line)
                lines.append(line)
        return lines```

Thanks.

**Comment by abhijeet3922** [comment]
With few experiments, I got it.

train, test and validation csv are in simple format i.e index, text, label separated by tab

**Comment by bernardmizzi** [comment]
Can you kindly provide the train, test and validate sets you used as I cannot construct them?

**Comment by mostafaelhoushi** [comment]
> Can you kindly provide the train, test and validate sets you used as I cannot construct them?

I randomly ordered the data, and arbitrarily a allocated different portions to `train.csv`, `validation.csv`, and `test.csv`:
[sentiment_data.zip](https://github.com/ProsusAI/finBERT/files/4817068/sentiment_data.zip)

**Comment by emes83** [comment]
> With few experiments, I got it.
> 
> train, test and validation csv are in simple format i.e index, text, label separated by tab



> With few experiments, I got it.
> 
> train, test and validation csv are in simple format i.e index, text, label separated by tab

Could you please share with me a working set of files? (train, validation, test), I'm stuck and I don't know how to fix it.

**Comment by hrushiz** [comment]
@abhijeet3922 Can you please share the test, train and validation csv files as a zip file? Thanks!

**Comment by abhijeet3922** [comment]
Hello everyone.
Please find the constructed train.csv, test.csv and dev,csv from [here](https://github.com/fidelity/classitransformers/tree/master/datasets/financial_phrasebank).
