### ISSUE TITLE
pip install transformers is necessary to Dockerfile

### ISSUE THREAD

**Issue by MatShin** [ProsusAI/finBERT#52]
Hello. I just would like to report you that running container created by image built from Dockerfile in current master repository would cause an ModuleNotFoundError.

I solved this issue by changing code in Dockerfile.

Before:
`RUN pip install pytorch_pretrained_bert numpy pandas nltk Flask flask-cors`

After:
`RUN pip install pytorch_pretrained_bert numpy pandas nltk Flask flask-cors transformers`

I would appreciate if you check it out.

**Comment by doguaraci** [comment]
Thanks @MatShin !
