### ISSUE TITLE
error using predict.py

### ISSUE THREAD

**Issue by m1996** [ProsusAI/finBERT#53]
hi, I tried to run predict.py by: 
!python predict.py --text_path="test.txt" --output_dir="output/" --model_path="pytorch_model.bin" 
,as you said in readme

but I got the following error:
usage: predict.py [-h] [--data_path DATA_PATH]
predict.py: error: unrecognized arguments: --text_path=test.txt --output_dir=output/ --model_path=pytorch_model.bin

what is the problem? it looks like it is using another file but I can't figured out which and why!
would you please help me?
regards

**Comment by doguaraci** [comment]
Hi, the problem is with `model_path`. The model path should not be the `.bin` file but the folder that includes the `.bin` and `config` files.

**Comment by m1996** [comment]
thanks for your response
I made a folder named "model" which has `pytorch_model.bin` and `config.json`.
then I tried:
`!python predict.py --text_path="./test.txt" --output_dir="./output/" --model_path="./model"`
but still getting:
```
usage: predict.py [-h] [--data_path DATA_PATH]
predict.py: error: unrecognized arguments: --text_path=./test.txt --output_dir=./output/ --model_path=./model

```
when I try `!python predict.py -h`, I get:
```
usage: predict.py [-h] [--data_path DATA_PATH]

Sentiment analyzer

optional arguments:
  -h, --help            show this help message and exit
  --data_path DATA_PATH
                        Path to the text file.

```
looks like only wants one input but when I try with 1 input I get another error...
what am I doing wrong?

**Comment by m1996** [comment]
by the way, I move out predict.py and dataset.py from scripts folder to the main one.
And I am using colab so I did not make environment and simply !pip install all the dependencies:
```
!pip install jupyter==1.0.0
!pip install pandas==0.23.4
!pip install python==3.7.3
!pip install numpy==1.16.3
!pip install nltk
!pip install tqdm
!pip install ipykernel==5.1.3
!pip install transformers==4.1.1
!pip install joblib==0.13.2
!pip install scikit-learn==0.21.2
!pip install spacy==2.1.4
!pip install torch==1.1.0
!pip install textblob
```

is problem with these?

**Comment by m1996** [comment]
Hi, I've found the problem. I did as you said AND moved `datasets.py` to `scripts `folder and kept` predict.py` in the main folder.
then it run:))) but I got another error which fixed by 
```
import nltk
nltk.download('punkt')
```

thank you so much. I will close the issue.
