### ISSUE TITLE
no code for FiQA sentiment classification task?

### ISSUE THREAD

**Issue by Dodo-Cho** [ProsusAI/finBERT#54]
I did not find code for FiQA aspects-based sentiment task, and wonder how roberta model handle aspects-based sentiment task which is different from vanilla sentiment classification task. Thanks a lot

**Comment by doguaraci** [comment]
Hi, yes the code on the repo is only for classification. On FiQA dataset, I just approached it as a regression task, without taking aspects and targets into account.
