### ISSUE TITLE
lm_fine_tuning

### ISSUE THREAD

**Issue by vr25** [ProsusAI/finBERT#6]
Hi,

With reference to my previous issue posted [here](https://github.com/ProsusAI/finBERT/issues/1), I followed what you suggested but I am still couldn't fine_tune on my sample domain. I was wondering if you could take a look at [this](https://github.com/huggingface/transformers/issues/1907).

Thanks!

**Comment by bernardmizzi** [comment]
@vr25 what exactly are you trying to do to pretrain BERT on your domain? As I cannot find a way how to start
