### ISSUE TITLE
Tokenizer

### ISSUE THREAD

**Issue by pepi99** [ProsusAI/finBERT#64]
Hello!
Since FinBERT is further trained on BERT, and the original BERT has its own tokenizer, I suppose you are not training your own tokenizer to train the model, right? Otherwise, the model might get confused since the original model was trained with a different tokenizer.

**Comment by doguaraci** [comment]
Yes, we’re using BERT tokenizer.

**Comment by pepi99** [comment]
This is very useful to know. Thank you and have a good day.
