### ISSUE TITLE
Unable to run finbert on R 

### ISSUE THREAD

**Issue by Asmaphd** [ProsusAI/finBERT#70]
Error: Failed to install 'unknown package' from GitHub:
  HTTP error 404.
  Not Found

  Did you spell the repo owner (`yiyanghkust`) and repo name (`FinBERT`) correctly?
  - If spelling is correct, check that you have the required permissions to access the repo.
Encountering this on R studio please help me

**Comment by doguaraci** [comment]
Hello, I don't really know how huggingface models work with Rstudio, so won't be able to help unfortunately. 
Also a note: the finbert model that is the same as what we have on this repo is this one: [https://huggingface.co/ProsusAI/finbert](https://huggingface.co/ProsusAI/finbert) , so the issue might be stemming from that.
